from __future__ import annotations

from typing import Protocol

from src.domain.role_entities import Role, User


class RoleRepository(Protocol):
    def create_role(self, name: str, description: str = "") -> Role: ...

    def get_all_roles(self) -> list[Role]: ...

    def get_role_by_id(self, role_id: int) -> Role | None: ...

    def update_role(self, role_id: int, name: str, description: str) -> Role | None: ...

    def delete_role(self, role_id: int) -> bool: ...

    def create_user(self, username: str, email: str) -> User: ...

    def get_all_users(self) -> list[User]: ...

    def assign_role_to_user(self, user_id: int, role_id: int) -> bool: ...

    def revoke_role_from_user(self, user_id: int, role_id: int) -> bool: ...

    def set_user_active(self, user_id: int, is_active: bool) -> bool: ...
